openapi: 3.0.0
info:
  title: HackRx 2.0
  contact: {}
  version: '1.0'
servers:
- url: https://hrxapi.chetanpareek.tech
  variables: {}
- url: http://localhost:3500/api
  variables: {}
- url: http://example.com/api/doctor
  variables: {}
paths:
  /:
    get:
      tags:
      - Misc
      summary: home route
      operationId: homeroute
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
  /api/doctor:
    post:
      tags:
      - Misc
      summary: send doctor details
      operationId: senddoctordetails
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/senddoctordetailsrequest'
            example:
              name: Chetan Pareek
              username: cp99says
              password: hala_madrid
              speciality: dermatologist
              address: place named none of your business
              email: chetan@bajaj.com
              phone: 7458963259
              fee: 1600
              experience: 8
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
    get:
      tags:
      - Misc
      summary: get all doctor details
      operationId: getalldoctordetails
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
  /login:
    post:
      tags:
      - Misc
      summary: Login API
      operationId: LoginAPI
      parameters:
      - name: email
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: chetan@bajaj.com
      - name: role
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: doctor
      - name: password
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: hala_madrid
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: http://localhost:3500/api
        variables: {}
  /username:
    get:
      tags:
      - Misc
      summary: get doctor by username
      operationId: getdoctorbyusername
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: atif@jayaho
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: http://example.com/api/doctor
        variables: {}
  /api/doctor/speciality:
    get:
      tags:
      - Misc
      summary: get doctor by speciality
      operationId: getdoctorbyspeciality
      parameters:
      - name: speciality
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: sexologist
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
  /api/doctor/status:
    get:
      tags:
      - Misc
      summary: get doctor by status
      operationId: getdoctorbystatus
      parameters:
      - name: status
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 0
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
  /api/doctor/fee/lt:
    get:
      tags:
      - Misc
      summary: get doctors with fee less than amount
      operationId: getdoctorswithfeelessthanamount
      parameters:
      - name: value
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 600
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
  /api/doctor/fee/gt:
    get:
      tags:
      - Misc
      summary: get doctors with fee greater than amount
      operationId: getdoctorswithfeegreaterthanamount
      parameters:
      - name: value
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1800
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
  /experience/lt:
    get:
      tags:
      - Misc
      summary: get doctor with  experience less than time
      operationId: getdoctorwithexperiencelessthantime
      parameters:
      - name: value
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 2
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: http://example.com/api/doctor
        variables: {}
  /experience/gt:
    get:
      tags:
      - Misc
      summary: get doctor with  experience greater than time
      operationId: getdoctorwithexperiencegreaterthantime
      parameters:
      - name: value
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 7
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: http://example.com/api/doctor
        variables: {}
  /api/patient:
    post:
      tags:
      - Misc
      summary: send patient details
      operationId: sendpatientdetails
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendpatientdetailsrequest'
            example:
              name: Harshit Aggarwal
              username: ha5409@srm
              password: hala_madrid
              email: ha5409@srm.co.in
              phone: 17891497854
              address: California, USA
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
    get:
      tags:
      - Misc
      summary: get all patient details
      operationId: getallpatientdetails
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
  /api/patient/username:
    get:
      tags:
      - Misc
      summary: get patient by username
      operationId: getpatientbyusername
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: jeff@amazon
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
  /api/patient/send_medical_details:
    post:
      tags:
      - Misc
      summary: send medical details with username and description id
      operationId: sendmedicaldetailswithusernameanddescriptionid
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: jeff@amazon
      - name: id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: random id
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://hrxapi.chetanpareek.tech
        variables: {}
components:
  schemas:
    senddoctordetailsrequest:
      title: senddoctordetailsrequest
      required:
      - name
      - username
      - password
      - speciality
      - address
      - email
      - phone
      - fee
      - experience
      type: object
      properties:
        name:
          type: string
        username:
          type: string
        password:
          type: string
        speciality:
          type: string
        address:
          type: string
        email:
          type: string
        phone:
          type: integer
          format: int64
        fee:
          type: integer
          format: int32
        experience:
          type: integer
          format: int32
      example:
        name: Chetan Pareek
        username: cp99says
        password: hala_madrid
        speciality: dermatologist
        address: place named none of your business
        email: chetan@bajaj.com
        phone: 7458963259
        fee: 1600
        experience: 8
    sendpatientdetailsrequest:
      title: sendpatientdetailsrequest
      required:
      - name
      - username
      - password
      - email
      - phone
      - address
      type: object
      properties:
        name:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        phone:
          type: integer
          format: int64
        address:
          type: string
      example:
        name: Harshit Aggarwal
        username: ha5409@srm
        password: hala_madrid
        email: ha5409@srm.co.in
        phone: 17891497854
        address: California, USA
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
- httpBearer: []
tags:
- name: Misc
  description: ''